apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DB_PASSWORD: {{ printf .Values.postgresql.postgresqlPassword  | b64enc | quote }}