apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  DB_HOST: {{ (include "postgresql.fullname" .) }}
  DB_PORT: {{ .Values.postgresql.service.port | toYaml | indent 4 }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase | toYaml | indent 4 }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername | toYaml | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DB_PASSWORD: {{  printf "%s" .Values.postgresql.postgresqlPassword  | b64enc | quote }}