apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-py-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
  type: {{ .Values.service.type }}

