apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  DB_HOST: postgres
  DB_PORT: '5432'
  DB_NAME: myapp
  DB_USER: myuser
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dk