apiVersion: batch/v1
kind: Job
metadata:
  name: "myapp"
spec:
  template:
    metadata:
      name: "myapp"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "passwd"
          command:
            - sh
            - "-c"
            - |
              psql postgres://myuser:passwd@postgres/myapp <<'EOF'
                create table students (id serial primary key, name varchar);
                insert into students (id, name) values (1, 'Konstantin');
              EOF
  backoffLimit: 0