apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
    - image: scpigo/testk8sapp
      context: ../app
deploy:
  kubectl:
    manifests:
      - app-config.yaml
      - deployment.yaml
      - service.yaml
      - ingress.yaml
      - postgres.yaml